title: Technical Documentation
description: End to End documentation of backend.
remote_theme: just-the-docs/just-the-docs

# Enable search
search_enabled: true

# Color scheme
color_scheme: dark


# Navigation
nav_enabled: true

# Footer
footer_content: "Copyright &copy; 2025 Stanza Soft"
